-- setting unique index when deleted is true
ALTER TABLE roles DROP CONSTRAINT IF EXISTS roles_name_deleted_uindex;
ALTER TABLE attachment DROP CONSTRAINT IF EXISTS attachment_path_file_deleted_unique_index;
ALTER TABLE auth_user DROP CONSTRAINT IF EXISTS auth_user_username_deleted_unique_index;
ALTER TABLE region DROP CONSTRAINT IF EXISTS region_name_deleted_unique_index;
ALTER TABLE district DROP CONSTRAINT IF EXISTS district_name_deleted_unique_index;

CREATE UNIQUE INDEX roles_name_deleted_uindex ON roles (name, deleted) WHERE deleted = FALSE;
CREATE UNIQUE INDEX attachment_path_file_deleted_unique_index ON attachment (path_file, deleted) WHERE deleted = FALSE;
CREATE UNIQUE INDEX auth_user_username_deleted_unique_index ON auth_user (username, deleted) WHERE deleted = FALSE;
CREATE UNIQUE INDEX region_name_deleted_unique_index ON region (name, deleted) WHERE deleted = FALSE;
CREATE UNIQUE INDEX district_name_deleted_unique_index ON district (name, deleted) WHERE deleted = FALSE;

-- Auto filling of regions and districts of Uzbekistan
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1726, now(), 0, false, 'Toshkent shahri');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1703, now(), 0, false, 'Andijon viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1730, now(), 0, false, 'Farg‘ona viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1712, now(), 0, false, 'Navoiy viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1735, now(), 0, false, 'Qoraqalpog‘iston Respublikasi');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1724, now(), 0, false, 'Sirdaryo viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1733, now(), 0, false, 'Xorazm viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1727, now(), 0, false, 'Toshkent viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1722, now(), 0, false, 'Surxondaryo viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1710, now(), 0, false, 'Qashqadaryo viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1718, now(), 0, false, 'Samarqand viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1714, now(), 0, false, 'Namangan viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1708, now(), 0, false, 'Jizzax viloyati');
INSERT INTO region("id", "created_at", "created_by", "deleted", "name") VALUES (1706, now(), 0, false, 'Buxoro viloyati');

INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703002, now(), 0, false, 'Qorasuv shahri', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703202, now(), 0, false, 'Oltinko''l tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703203, now(), 0, false, 'Andijon tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703206, now(), 0, false, 'Baliqchi tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703209, now(), 0, false, 'Bo''ston tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703210, now(), 0, false, 'Buloqboshi tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703211, now(), 0, false, 'Jalaquduq tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703214, now(), 0, false, 'Izboskan tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703217, now(), 0, false, 'Ulug''nor tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703220, now(), 0, false, 'Qo''rg''ontepa tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703224, now(), 0, false, 'Asaka tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703227, now(), 0, false, 'Marxamat tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703230, now(), 0, false, 'Shaxrixon tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703232, now(), 0, false, 'Paxtaobod tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703236, now(), 0, false, 'Xo''jaobod tumani', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703401, now(), 0, false, 'Andijon shahri', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1703408, now(), 0, false, 'Xonobod shahri', 1703);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706204, now(), 0, false, 'Olot tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706207, now(), 0, false, 'Buxoro tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706212, now(), 0, false, 'Vobkent tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706215, now(), 0, false, 'G''ijduvon tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706219, now(), 0, false, 'Kogon tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706230, now(), 0, false, 'Qorako''l tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706232, now(), 0, false, 'Qorovulbozor tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706240, now(), 0, false, 'Peshku tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706242, now(), 0, false, 'Romitan tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706246, now(), 0, false, 'Jondor tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706258, now(), 0, false, 'Shofirkon tumani', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706401, now(), 0, false, 'Buxoro shahri', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1706403, now(), 0, false, 'Kogon shahri', 1706);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708201, now(), 0, false, 'Arnasoy tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708204, now(), 0, false, 'Baxmal tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708209, now(), 0, false, 'G''allaorol tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708212, now(), 0, false, 'Sharof Rashidov tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708215, now(), 0, false, 'Do''stlik tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708218, now(), 0, false, 'Zomin tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708220, now(), 0, false, 'Zarbdor tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708223, now(), 0, false, 'Mirzacho''l tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708225, now(), 0, false, 'Zafarobod tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708228, now(), 0, false, 'Paxtakor tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708235, now(), 0, false, 'Forish tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708237, now(), 0, false, 'Yangiobod tumani', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1708401, now(), 0, false, 'Jizzax shahri', 1708);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710207, now(), 0, false, 'G''uzor tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710212, now(), 0, false, 'Dehqonobod tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710220, now(), 0, false, 'Qamashi tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710224, now(), 0, false, 'Qarshi tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710229, now(), 0, false, 'Koson tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710232, now(), 0, false, 'Kitob tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710233, now(), 0, false, 'Mirishkor tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710234, now(), 0, false, 'Muborak tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710235, now(), 0, false, 'Nishon tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710237, now(), 0, false, 'Kasbi tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710240, now(), 0, false, 'Ko‘kdala tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710242, now(), 0, false, 'Chiroqchi tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710243, now(), 0, false, 'Kukdala tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710245, now(), 0, false, 'Shahrisabz tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710250, now(), 0, false, 'Yakkabog'' tumani', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710401, now(), 0, false, 'Qarshi shahri', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1710405, now(), 0, false, 'Shahrisabz shahri', 1710);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712211, now(), 0, false, 'Konimex tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712216, now(), 0, false, 'Qiziltepa tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712230, now(), 0, false, 'Navbahor tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712234, now(), 0, false, 'Karmana tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712238, now(), 0, false, 'Nurota tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712244, now(), 0, false, 'Tomdi tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712248, now(), 0, false, 'Uchquduq tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712251, now(), 0, false, 'Xatirchi tumani', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712401, now(), 0, false, 'Navoiy shahri', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712408, now(), 0, false, 'Zarafshon shahri', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1712412, now(), 0, false, 'G''ozg''on shahri', 1712);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714204, now(), 0, false, 'Mingbuloq tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714207, now(), 0, false, 'Kosonsoy tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714212, now(), 0, false, 'Namangan tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714216, now(), 0, false, 'Norin tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714219, now(), 0, false, 'Pop tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714224, now(), 0, false, 'To''raqo''rg''on tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714229, now(), 0, false, 'Uychi tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714234, now(), 0, false, 'Uchqo''rg''on tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714236, now(), 0, false, 'Chortoq tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714237, now(), 0, false, 'Chust tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714242, now(), 0, false, 'Yangiqo''rg''on tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714401, now(), 0, false, 'Namangan shahri', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714402, now(), 0, false, 'Davlatobod tumani', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1714403, now(), 0, false, 'Yangi Namangan tumami', 1714);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718203, now(), 0, false, 'Oqdaryo tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718206, now(), 0, false, 'Bulung''ur tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718209, now(), 0, false, 'Jomboy tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718212, now(), 0, false, 'Ishtixon tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718215, now(), 0, false, 'Kattaqo''rg''on tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718216, now(), 0, false, 'Qo''shrabot tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718218, now(), 0, false, 'Narpay tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718224, now(), 0, false, 'Payariq tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718227, now(), 0, false, 'Pastdarg''om tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718230, now(), 0, false, 'Paxtachi tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718233, now(), 0, false, 'Samarqand tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718235, now(), 0, false, 'Nurobod tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718236, now(), 0, false, 'Urgut tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718238, now(), 0, false, 'Tayloq tumani', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718401, now(), 0, false, 'Samarqand shahri', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1718406, now(), 0, false, 'Kattaqo''rg''on shahri', 1718);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722201, now(), 0, false, 'Oltinsoy tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722202, now(), 0, false, 'Angor tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722203, now(), 0, false, 'Bandixon tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722204, now(), 0, false, 'Boysun tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722207, now(), 0, false, 'Muzrabot tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722210, now(), 0, false, 'Denov tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722212, now(), 0, false, 'Jarqo''rg''on tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722214, now(), 0, false, 'Qumqo''rg''on tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722215, now(), 0, false, 'Qiziriq tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722217, now(), 0, false, 'Sariosiyo tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722220, now(), 0, false, 'Termiz tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722221, now(), 0, false, 'Uzun tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722223, now(), 0, false, 'Sherobod tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722226, now(), 0, false, 'Sho''rchi tumani', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1722401, now(), 0, false, 'Termiz shahri', 1722);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724206, now(), 0, false, 'Oqoltin tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724212, now(), 0, false, 'Boyovut tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724216, now(), 0, false, 'Sayxunobod tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724220, now(), 0, false, 'Guliston tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724226, now(), 0, false, 'Sardoba tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724228, now(), 0, false, 'Mirzaobod tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724231, now(), 0, false, 'Sirdaryo tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724235, now(), 0, false, 'Xovos tumani', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724401, now(), 0, false, 'Guliston shahri', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724410, now(), 0, false, 'Shirin shahri', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724413, now(), 0, false, 'Yangiyer shahri', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1724414, now(), 0, false, 'Baxt shahri', 1724);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726262, now(), 0, false, 'Uchtepa tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726264, now(), 0, false, 'Bektemir tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726266, now(), 0, false, 'Yunusobod tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726269, now(), 0, false, 'Mirzo Ulug''bek tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726273, now(), 0, false, 'Mirobod tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726277, now(), 0, false, 'Shayxontohur tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726280, now(), 0, false, 'Olmazor tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726283, now(), 0, false, 'Sirg''ali tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726287, now(), 0, false, 'Yakkasaroy tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726290, now(), 0, false, 'Yashnobod tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726292, now(), 0, false, 'Yangihayot tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1726294, now(), 0, false, 'Chilonzor tumani', 1726);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727206, now(), 0, false, 'Oqqo''rg''on tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727212, now(), 0, false, 'Ohangaron tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727220, now(), 0, false, 'Bekobod tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727224, now(), 0, false, 'Bo''stonliq tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727228, now(), 0, false, 'Bo''ka tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727233, now(), 0, false, 'Quyichirchiq tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727237, now(), 0, false, 'Zangiota tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727239, now(), 0, false, 'Yuqorichirchiq tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727248, now(), 0, false, 'Qibray tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727249, now(), 0, false, 'Parkent tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727250, now(), 0, false, 'Piskent tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727253, now(), 0, false, 'O''rtachirchiq tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727256, now(), 0, false, 'Chinoz tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727259, now(), 0, false, 'Yangiyo''l tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727265, now(), 0, false, 'Toshkent tumani', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727401, now(), 0, false, 'Nurafshon shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727404, now(), 0, false, 'Olmaliq shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727407, now(), 0, false, 'Angren shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727413, now(), 0, false, 'Bekobod shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727415, now(), 0, false, 'Ohangaron shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727419, now(), 0, false, 'Chirchiq shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1727424, now(), 0, false, 'Yangiyo''l shahri', 1727);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730203, now(), 0, false, 'Oltiariq tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730206, now(), 0, false, 'Qo''shtepa tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730209, now(), 0, false, 'Bog''dod tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730212, now(), 0, false, 'Buvayda tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730215, now(), 0, false, 'Beshariq tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730218, now(), 0, false, 'Quva tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730221, now(), 0, false, 'Uchko''prik tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730224, now(), 0, false, 'Rishton tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730226, now(), 0, false, 'So''x tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730227, now(), 0, false, 'Toshloq tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730230, now(), 0, false, 'O''zbekiston tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730233, now(), 0, false, 'Farg''ona tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730236, now(), 0, false, 'Dang''ara tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730238, now(), 0, false, 'Furqat tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730242, now(), 0, false, 'Yozyovon tumani', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730401, now(), 0, false, 'Farg''ona shahri', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730405, now(), 0, false, 'Qo''qon shahri', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730408, now(), 0, false, 'Quvasoy shahri', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1730412, now(), 0, false, 'Marg''ilon shahri', 1730);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733204, now(), 0, false, 'Bog''ot tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733208, now(), 0, false, 'Gurlan tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733212, now(), 0, false, 'Qo''shko''pir tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733217, now(), 0, false, 'Urganch tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733220, now(), 0, false, 'Hazorasp tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733221, now(), 0, false, 'Tuproqqal''a tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733223, now(), 0, false, 'Xonqa tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733226, now(), 0, false, 'Xiva tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733230, now(), 0, false, 'Shovot tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733233, now(), 0, false, 'Yangiariq tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733236, now(), 0, false, 'Yangibozor tumani', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733401, now(), 0, false, 'Urganch shahri', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733406, now(), 0, false, 'Xiva shahri', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1733407, now(), 0, false, 'Pitnak shahri', 1733);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735204, now(), 0, false, 'Amudaryo tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735207, now(), 0, false, 'Beruniy tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735209, now(), 0, false, 'Bo‘zatov tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735211, now(), 0, false, 'Qorao''zak tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735212, now(), 0, false, 'Kegeyli tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735215, now(), 0, false, 'Qo''ng''irot tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735218, now(), 0, false, 'Qanliko''l tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735222, now(), 0, false, 'Mo''ynoq tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735225, now(), 0, false, 'Nukus tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735228, now(), 0, false, 'Taxiatosh tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735230, now(), 0, false, 'Taxtako''pir tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735233, now(), 0, false, 'To''rtko''l tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735236, now(), 0, false, 'Xo''jayli tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735240, now(), 0, false, 'Chimboy tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735243, now(), 0, false, 'Shumanay tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735250, now(), 0, false, 'Ellikqal''a tumani', 1735);
INSERT INTO district("id", "created_at", "created_by", "deleted", "name", "region_id") VALUES (1735401, now(), 0, false, 'Nukus shahri', 1735);
